//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computer_Games
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Player = new HashSet<Player>();
            this.Teams = new HashSet<Teams>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int CountryID { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<Player> Player { get; set; }
        public virtual ICollection<Teams> Teams { get; set; }
    }
}
