//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computer_Games
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coaches
    {
        public Coaches()
        {
            this.CoachTrain = new HashSet<CoachTrain>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public int CountryID { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<CoachTrain> CoachTrain { get; set; }
    }
}
