//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computer_Games
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoachTrain
    {
        public int ID { get; set; }
        public int CoachID { get; set; }
        public int TeamID { get; set; }
        public System.DateTime DateBegin { get; set; }
        public System.DateTime DateEnd { get; set; }
    
        public virtual Coaches Coaches { get; set; }
        public virtual Teams Teams { get; set; }
    }
}
