//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computer_Games
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetitionsGamers
    {
        public int ID { get; set; }
        public int GamerID { get; set; }
        public int CompetitionID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> PrizeID { get; set; }
    
        public virtual Competition1 Competition1 { get; set; }
        public virtual CompetitionsGamers CompetitionsGamers1 { get; set; }
        public virtual CompetitionsGamers CompetitionsGamers2 { get; set; }
        public virtual Player Player { get; set; }
        public virtual Prizes Prizes { get; set; }
    }
}
