//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computer_Games
{
    using System;
    using System.Collections.Generic;
    
    public partial class GamerStuding
    {
        public int ID { get; set; }
        public int GamerID { get; set; }
        public int SchoolID { get; set; }
        public Nullable<int> StudingBegin { get; set; }
        public Nullable<int> StudingEnd { get; set; }
        public Nullable<int> StudyBegin { get; set; }
        public Nullable<int> StudyEnd { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Schools Schools { get; set; }
    }
}
