//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computer_Games
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games
    {
        public Games()
        {
            this.Championship1 = new HashSet<Championship1>();
            this.Competition1 = new HashSet<Competition1>();
        }
    
        public int ID { get; set; }
        public string GameName { get; set; }
        public int ReleaseYear { get; set; }
        public string Versions { get; set; }
        public string ComputersThatSupport { get; set; }
    
        public virtual ICollection<Championship1> Championship1 { get; set; }
        public virtual ICollection<Competition1> Competition1 { get; set; }
    }
}
