//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computer_Games
{
    using System;
    using System.Collections.Generic;
    
    public partial class Iron
    {
        public Iron()
        {
            this.Results = new HashSet<Results>();
            this.Results1 = new HashSet<Results>();
        }
    
        public int ID { get; set; }
        public string IronName { get; set; }
    
        public virtual ICollection<Results> Results { get; set; }
        public virtual ICollection<Results> Results1 { get; set; }
    }
}
