//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computer_Games
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class computer_gamesEntities : DbContext
    {
        public computer_gamesEntities()
            : base("name=computer_gamesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Championship> Championship { get; set; }
        public DbSet<Championship1> Championship1 { get; set; }
        public DbSet<City> City { get; set; }
        public DbSet<Coaches> Coaches { get; set; }
        public DbSet<CoachTrain> CoachTrain { get; set; }
        public DbSet<Competition> Competition { get; set; }
        public DbSet<Competition1> Competition1 { get; set; }
        public DbSet<CompetitionsGamers> CompetitionsGamers { get; set; }
        public DbSet<CompetitionsTeams> CompetitionsTeams { get; set; }
        public DbSet<Country> Country { get; set; }
        public DbSet<GamerStuding> GamerStuding { get; set; }
        public DbSet<Games> Games { get; set; }
        public DbSet<Iron> Iron { get; set; }
        public DbSet<Nominations> Nominations { get; set; }
        public DbSet<People> People { get; set; }
        public DbSet<Player> Player { get; set; }
        public DbSet<Prizes> Prizes { get; set; }
        public DbSet<Results> Results { get; set; }
        public DbSet<Schools> Schools { get; set; }
        public DbSet<Stages> Stages { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Teams> Teams { get; set; }
        public DbSet<TeamsGamers> TeamsGamers { get; set; }
        public DbSet<TeamsPlay> TeamsPlay { get; set; }
        public DbSet<TeamsPrizes> TeamsPrizes { get; set; }
    }
}
