//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computer_Games
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.CompetitionsGamers = new HashSet<CompetitionsGamers>();
            this.GamerStuding = new HashSet<GamerStuding>();
            this.TeamsGamers = new HashSet<TeamsGamers>();
        }
    
        public int ID { get; set; }
        public System.DateTime Birthday { get; set; }
        public int CityID { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string ThirdName { get; set; }
        public string Photo { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<CompetitionsGamers> CompetitionsGamers { get; set; }
        public virtual ICollection<GamerStuding> GamerStuding { get; set; }
        public virtual ICollection<TeamsGamers> TeamsGamers { get; set; }
    }
}
