//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computer_Games
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamsPlay
    {
        public int ID { get; set; }
        public int TeamID { get; set; }
        public int CompetitionID { get; set; }
        public System.DateTime Date { get; set; }
        public string Prize { get; set; }
    
        public virtual Competition1 Competition1 { get; set; }
        public virtual Teams Teams { get; set; }
    }
}
